### ISSUE TITLE
[PE-D][Tester B] Unable to enter command when editing to assign duplicate nickname

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#238]
State: Users with differing full names
Action: Edit one user to have the same nickname of another user.
Result:Pressing enter does not produce any visible behaviour, no messages given.
Possible solution: Include an error message to tell the user of the duplicate nickname (similar to when setting users with the same full name to the same nick name)
![image.png](https://raw.githubusercontent.com/itsme-zeix/ped/main/files/cd449e3e-6d0f-454b-a162-f31c73534f79.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: itsme-zeix/ped#2

**Comment by wuzengfu** [comment]
## Description
This issue is due to `DuplicateFieldException` inheriting `RuntimeException` as a result of the exception not being caught by `CommandException` in `EditCommand::execute`.

## Possible Solution
Inherit `DuplicateFieldException` from `CommandException` and update relevant method signatures to add the exception.

**Comment by somethingfishyfishy** [comment]
#277
